import os
import time
import pickle
import argparse
import random

n = random.random()

current_folder = os.getcwd()

config = {
    #'tile_dir': os.path.join(current_folder, f'tiles_{n}'),
    'tile_dir': '/mnt/iribhm/people/rcharkao/dim_red_comp/tiles_0.3469658067471243',
    'latent_dir': os.path.join(current_folder, f'results_{n}'),
    'pixplot_in_dir': os.path.join(current_folder, f'pixplot_input_{n}'),
    'pyramid_dir': os.path.join(current_folder, f'pyramid_{n}'),
    'tile_size': 224,
    'tile_resize': 224,
    'name_len':12,
    'processing_unit': 'cuda:1',
    'batch_size': 25,
    'num_workers': 5,
    'suffix_folder':'svs',
    'suffix_file':'csv',
    'no_valid_model': False,
    'cell_size': 16,
    'pc_sampled': 0.05,
    'zoom': 0.5,
    'set_seed': 520
}

def parse():
    '''Read command line args and begin data processing'''
    description = 'Create the data required to create a PixPlot viewer'
    parser = argparse.ArgumentParser(description=description, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--tiling', '-t', action='store_true', help='do tiling', required=False)
    parser.add_argument('--inference', '-i', action='store_true', help='do inference', required=False)
    parser.add_argument('--pixplot', '-p', action='store_true', help='do inference', required=False)
    parser.add_argument('--clean_inv', '-cin', action='store_true', help='clean generated inversed image at the end', required=False)
    parser.add_argument('--clean_pyramid', '-cpy', action='store_true', help='clean generated pyramid image at the end', required=False)
    parser.add_argument('--clean_tiling', '-ct', action='store_true', help='clean generated tiles at the end', required=False)
    parser.add_argument('--clean_inference', '-ci', action='store_true', help='clean generated latent space at the end', required=False)
    parser.add_argument('--clean_pixplot', '-cp', action='store_true', help='clean generated pixplot input file at the end', required=False)
    parser.add_argument('--slide', '-s', type=str, nargs='+', help='path(s) to slide(s) or folder containing slide(s)')
    parser.add_argument('--model', '-m', type=str, help='path to model', required=False)
    parser.add_argument('--timm_model', '-tm', type=str, help='model name from timm', required=False)
    parser.add_argument('--tile_size', '-ts', type=int, default=config['tile_size'], help='size of tiles to be generated by tiling', required=False)
    parser.add_argument('--tile_resize', '-tr', type=int, default=config['tile_resize'], help='size to which the generated tiles will be resized', required=False)
    parser.add_argument('--name_len', '-nl', type=int, default=config['name_len'], help='length of slide name part to be considered to name the pixplot out dir', required=False)
    parser.add_argument('--fill_hole', '-fh', type=int, help='disk size to be applied during the holes filing operation', required=False)
    parser.add_argument('--remove_border', '-rb', type=int, help='disk size to be applied during the borders removal operation', required=False)
    parser.add_argument('--if', '-f', action='store_true', help='if image', required=False)
    parser.add_argument('--cell_size', '-cs', type=int, default=config['cell_size'], help='cell_size argument value in pixplot command', required=False)
    parser.add_argument('--tile_dir', '-td', type=str, default=config['tile_dir'], help='path to tiles folder if wiling to keep tiles generated', required=False)
    parser.add_argument('--latent_dir', '-ld', type=str, default=config['latent_dir'], help='path to latent folder if wiling to keep tiles generated', required=False)
    parser.add_argument('--pixplot_in_dir', '-pid', type=str, default=config['pixplot_in_dir'], help='path to pixplot input folder', required=False)
    parser.add_argument('--processing_unit', '-pu', type=str, default=config['processing_unit'], help='cpu or specify cuda location', required=False)
    parser.add_argument('--batch_size', '-bs', type=int, default=config['batch_size'], help='batch size to be loaded during model inference', required=False)
    parser.add_argument('--num_workers', '-nw', type=int, default=config['num_workers'], help='number of workers used for model inference', required=False)

    config.update(vars(parser.parse_args()))

def clean_inv(**config):
    os.system(f"rm -r {config['inv_dir']}")
    print('Inversed image cleaned')      
    
def clean_pyramid(**config):
    os.system(f"rm -r {config['pyramid_dir']}")
    print('Pyramids cleaned')  
    
def clean_tiles(**config):
    #print(config['tile_dir'])
    if config['tile_dir'] == os.path.join(current_folder, f'tiles_{n}'):
        os.system(f"rm -r {config['tile_dir']}")
        print('Tiles cleaned')  
    else:
        print("Tiles folder is not the default folder, can't be cleaned for security")
        
def clean_latent(**config):
    if config['latent_dir'] == os.path.join(current_folder, f'results_{n}'):
        os.system(f"rm -r {config['latent_dir']}")
        print('Latent space data cleaned')
    else:
        print("Latent space folder is not the default folder, can't be cleaned for security")

def clean_pixplot(**config):
    if config['pixplot_in_dir'] == os.path.join(current_folder, f'pixplot_input_{n}'):
        os.system(f"rm -r {config['pixplot_in_dir']}")
        print('Pixplot input file cleaned') 
    else:
        print("Pixplot input file folder is not the default folder, can't be cleaned for security")

def fill_blank(string):
    return string.replace(' ', '_')

if __name__ == '__main__':
    print('The pixplot pipeline has started')
    t0t = time.time()
    parse()
    #print(config)
    pickle.dump(config, open(os.path.join(current_folder, 'config.txt'), "wb"))
    
    os.system("singularity exec --nv /mnt/iribhm/software/singularity/pytorch-lightning.img python pixplot_pipeline.py")
    config=pickle.load(open(os.path.join(current_folder, 'config.txt'), "rb"))
    #print(config)
    print(config)
    if config['pixplot']==True and config['all_slide_names'] != None:
        count = len(config['all_slide_names'])
        nl = config['name_len']
        for i in range(count):
            slide_name = config['all_slide_names'][i]
            #tiles_metadata_file = config['all_tiles_metadata_files'][i]
            pixplot_input_file = config['all_pixplot_input_files'][i]
            if len(slide_name)>=nl:
                pixplot_out_dir = os.path.splitext(slide_name)[0][:nl+1] + '_' + str(config['model_name']) + '_' + str(config['tile_size'])
            if len(slide_name)<nl:
                pixplot_out_dir = os.path.splitext(slide_name)[0] + '_' + str(config['model_name']) + '_' + str(config['tile_size'])
            if ' ' in pixplot_out_dir:
                pixplot_out_dir = fill_blank(pixplot_out_dir)
            print(f'The pixplot output folder "{pixplot_out_dir}" is being generated.')  
            pixel_slide = config['all_pixel_slides'][i]
            pixplot_input_file = config['all_pixplot_input_files'][i]
            images_path_suffix = pixel_slide + '/' + f'processing/tiles/{slide_name}_tile_*png'
            images_path = os.path.join(config['tile_dir'], images_path_suffix)
            cell_size = config['cell_size']
            t0 = time.time()
            #print((f'singularity exec /mnt/iribhm/software/singularity/pixplot.sif pixplot --metadata "{pixplot_input_file}" --images "{images_path}" --out_dir "{pixplot_out_dir}" --cell_size {cell_size}'))
            os.system(f'singularity exec /mnt/iribhm/software/singularity/pixplot.sif pixplot --metadata "{pixplot_input_file}" --images "{images_path}" --out_dir "{pixplot_out_dir}" --cell_size {cell_size}')
            os.system(f'mv {pixplot_out_dir} /mnt/iribhm/public/www/ai/morphological-space/')
            print(f'The pixplot output folder "{pixplot_out_dir}" has been moved to "morphological-space" for visualization, you can now open in the browser https://www-hpda.ulb.ac.be/iribhm/ai/morphological-space/{pixplot_out_dir}/#') 
            tf = time.time() - t0
            print(f'Pixplot output folder generation time: {tf:.2f}s')
            
    if config['clean_pixplot'] or config['clean_inference'] or config['clean_tiling']:                                  
        print("The cleaning step has started, only data generated in default paths in current folder will be cleaned")  
        if config['clean_inv']==True:
            clean_inv(**config)
        
        if config['clean_pyramid']==True:
            clean_pyramid(**config)
        
        if config['clean_tiling']==True:
            clean_tiles(**config)
   
        if config['clean_inference']==True:
            clean_latent(**config)

        if config['clean_pixplot']==True:
            clean_pixplot(**config)
                                    
    
    tft = time.time() - t0t
    print(f'Total time: {tft:.2f}s')

        